#!/usr/bin/env python3
"""Row 4 (susemi-next-ui-lang): extract MenuCommon::Init's font statements verbatim.

The font runner must exercise the real Init font policy - the UseHQFont branch,
the merge destination and the missing-source warning - instead of a copied
predicate, so this tool lifts the contiguous production region out of
`OptiScaler/menu/menu_common.cpp` and writes it to an include file that the
runner compiles:

  production-init-fonts.inc

Anchored on exact source markers: if a production line moves or is edited, the
anchors stop matching and this tool fails instead of silently testing stale code.

Exactly one documented substitution is applied, because the harness needs to
redirect the Hangul chain at the production call site without editing the
production source:

    Localization::RegisterHangulFont(io.Fonts)
 -> Localization::RegisterHangulFont(io.Fonts, g_hangulChain)

Everything else in the emitted region is byte-identical to the production source,
and both hashes (source file, emitted region) are written to the receipt.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

SOURCE = "OptiScaler/menu/menu_common.cpp"

REGION_START = "    if (io.Fonts->Fonts.empty() && Config::Instance()->UseHQFont.value_or_default())"
REGION_END = '        LOG_WARN("{}", Localization::MissingFontNotice());'

CHAIN_CALL = "Localization::RegisterHangulFont(io.Fonts)"
CHAIN_CALL_REDIRECTED = "Localization::RegisterHangulFont(io.Fonts, g_hangulChain)"

HEADER = f"""// GENERATED by tools/i18n_extract_fonts.py - production text, do not edit by hand.
//
// Source: {SOURCE} (MenuCommon::Init)
// Region: {REGION_START.strip()!r} .. {REGION_END.strip()!r}
//
// The harness must provide, in the scope that includes this file:
//   ImGuiIO& io;                            the menu's live ImGui IO
//   Config::Instance()                      a Config with UseHQFont/FontSize/TTFFontPath/OverlayMenu
//   float fontSize; bool _hdrTonemapApplied; the MenuCommon members the region writes
//   wstring_to_string(std::wstring)         the real helper lives in SysUtils.h
//   hack_compressed_compressed_data_base85   menu/font/Hack_Compressed.h
//   LOG_WARN(...)                            the runner's log sink
//   Localization::FontChain g_hangulChain;   the redirected Hangul chain
//
// One documented substitution:
//   {CHAIN_CALL}
//     -> {CHAIN_CALL_REDIRECTED}
// The redirect is what row 4's failure fixture asks for: the same production
// statements run against a chain that resolves nothing.
"""


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def line_span_of(source: str, start_marker: str, end_marker: str) -> tuple[int, int]:
    start_lines = [i for i, line in enumerate(source.splitlines()) if line == start_marker]
    end_lines = [i for i, line in enumerate(source.splitlines()) if line == end_marker]
    if len(start_lines) != 1:
        raise SystemExit(f"start anchor is not unique ({len(start_lines)} hits): {start_marker}")
    if len(end_lines) != 1:
        raise SystemExit(f"end anchor is not unique ({len(end_lines)} hits): {end_marker}")
    if end_lines[0] < start_lines[0]:
        raise SystemExit("end anchor precedes the start anchor")
    return start_lines[0], end_lines[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, help="worktree root")
    parser.add_argument("--out", required=True, help="path of production-init-fonts.inc to write")
    parser.add_argument("--evidence", help="optional JSON receipt path")
    arguments = parser.parse_args()

    root = pathlib.Path(arguments.root)
    source_path = root / SOURCE
    if not source_path.is_file():
        raise SystemExit(f"source not found: {source_path}")

    source_bytes = source_path.read_bytes()
    source = source_bytes.decode("utf-8")

    first, last = line_span_of(source, REGION_START, REGION_END)
    region = "\n".join(source.splitlines()[first : last + 1]) + "\n"

    hits = region.count(CHAIN_CALL)
    if hits != 1:
        raise SystemExit(f"the chain call appears {hits} times in the extracted region, expected exactly 1")

    emitted_region = region.replace(CHAIN_CALL, CHAIN_CALL_REDIRECTED)
    if CHAIN_CALL in emitted_region:
        raise SystemExit("the documented substitution did not apply")

    # The include sits inside a function body, so the region must not open a scope
    # the harness cannot close: check the braces balance on their own.
    if emitted_region.count("{") != emitted_region.count("}"):
        raise SystemExit("extracted region has unbalanced braces")

    out_path = pathlib.Path(arguments.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    header = HEADER + f"// source-sha256: {sha256_text(source_bytes.decode('utf-8'))}\n" \
                      f"// region-sha256: {sha256_text(region)}\n" \
                      f"// region-lines: {first + 1}-{last + 1}\n\n"
    out_path.write_bytes((header + emitted_region).encode("utf-8"))

    receipt = {
        "tool": "tools/i18n_extract_fonts.py",
        "schema": 1,
        "source": SOURCE,
        "source_sha256": sha256_text(source_bytes.decode("utf-8")),
        "region_lines": [first + 1, last + 1],
        "region_sha256": sha256_text(region),
        "emitted_sha256": sha256_text(header + emitted_region),
        "substitutions": [
            {"from": CHAIN_CALL, "to": CHAIN_CALL_REDIRECTED, "count": hits, "reason": "harness chain redirect"}
        ],
        "ascii_only": all(ord(character) < 128 for character in emitted_region),
        "out": arguments.out,
    }

    if arguments.evidence:
        evidence_path = pathlib.Path(arguments.evidence)
        evidence_path.parent.mkdir(parents=True, exist_ok=True)
        evidence_path.write_text(json.dumps(receipt, indent=1) + "\n", encoding="utf-8")

    print(f"extracted {SOURCE} lines {first + 1}-{last + 1} -> {arguments.out}")
    print(f"substitutions: {hits}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
